[theme]
base = "dark"
primaryColor = "#2d8bba"
backgroundColor = "#032542"
secondaryBackgroundColor = "#326084"
textColor = "#ffffff"
font = "sans serif"


[server]
address = "0.0.0.0"
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false